
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testAI3DBlock)
	add_subdirectory(testAI3DBlock)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testOSGNodeCollect)
 	add_subdirectory(testOSGNodeCollect)
 endif()
 if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testRenameModelName)
 	add_subdirectory(testRenameModelName)
 endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testAI3DImportGcp)
	add_subdirectory(testAI3DImportGcp)
endif()
 if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testSimplifyBlock)
 	add_subdirectory(testSimplifyBlock)
 endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/Core)
	add_subdirectory(Core)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testProj)

	add_subdirectory(testProj)
endif()

if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testPano)
	add_subdirectory(testPano)
endif()

if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/LodTree)
	add_subdirectory(LodTree)
endif()

if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testHist)
	add_subdirectory(testHist)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testTiling)
	add_subdirectory(testTiling)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testConvertTo3DView)
	add_subdirectory(testConvertTo3DView)
endif()

if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testOSGEditor)
	add_subdirectory(testOSGEditor)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testProjTemp)
	add_subdirectory(testProjTemp)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testMergeModel)
	add_subdirectory(testMergeModel)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testPackage)
	add_subdirectory(testPackage)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testXML2Colmap)
	add_subdirectory(testXML2Colmap)
endif()
#if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testXML2Colmap2)
#	add_subdirectory(testXML2Colmap2)
#endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testKMLIO)
	add_subdirectory(testKMLIO)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testExifIO)
	add_subdirectory(testExifIO)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/MokTools)
	add_subdirectory(MokTools)
endif()
if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testBoostFilesystem)
	add_subdirectory(testBoostFilesystem)
endif()

if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testDeviceInfo)
	add_subdirectory(testDeviceInfo)
endif()

if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testGenTask)
	add_subdirectory(testGenTask)
endif()

if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testGenTaskFullFlow)
	add_subdirectory(testGenTaskFullFlow)
endif()

#if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testPoints)
#	add_subdirectory(testPointManager)
#endif()
#
#if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testPoints)
#	add_subdirectory(testFreezeSubmit)
#endif()
#
#if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testPoints)
#	add_subdirectory(testSettleEngine)
#endif()
#
#if(EXISTS  ${CMAKE_CURRENT_SOURCE_DIR}/testPoints)
#	add_subdirectory(testPointsDistributed)
#endif()

