#ifndef _AI3D_CORE_FILE_H_
#define _AI3D_CORE_FILE_H_



#include <fstream>
#include <filesystem>
#include <iostream>
#include <cstdio>
#include <string>
#include <vector>
#include <cstdarg>
#include <boost/algorithm/string.hpp>

#include <Constants.h>
#include "Core/Endian.h"
#include "Core/Logging.h"
#include "Core/String.h"
#include "Core/Types.h"
#ifdef _MSC_VER
#include <io.h>
#else
#include <unistd.h>
#include <dirent.h>
#endif

namespace AI3D
{
    namespace CORE
    {
#ifndef STRINGIFY
#define STRINGIFY(s) STRINGIFY_(s)
#define STRINGIFY_(s) #s
#endif  
#define __T(x)      x

#define _T(x)       __T(x)
#define _TEXT(x)    __T(x)

#define PATH_SEPARATOR _T('/')
#define PATH_SEPARATOR_STR _T("/")
#define REVERSE_PATH_SEPARATOR _T('\\')
#define REVERSE_PATH_SEPARATOR_STR _T("\\")

        namespace detail {
            template <typename T>
            inline std::string JoinPathUtf8Segment(T const& t) {
                return std::string(t);
            }
        }

        class AI3D_API File
        {
        public:
            
            static std::string EnsureUnitPath(const std::string& path);
            static std::string  ToStringWithHighPrecision(double value, int precision = 16);
            
             static std::string  GetDirName(const std::string & path, bool isDir = true);
            
             static std::string  EnsureUnifySlash(const std::string & path);
           
             
             static std::string TrimUnifySlash(const std::string& path);
             
             static void GetLastSecondDir(const std::string& path, std::string& parentdir, std::string& lastdir, bool isDir = true);
             static std::string  AutoGeneratedFullFilePath(std::string currFilePath, std::string currFileName, bool& isnew);
             static bool IsFileExistent(const std::string& filename);
             bool IsFileExistent_1(const std::string& filename);

            
            static std::string  EnsureTrailingSlash(const std::string& str);

            
            static bool  HasFileExtension(const std::string& file_name, const std::string& ext);

            
            
            static void  SplitFileExtension(const std::string& path, std::string* root,
                std::string* ext);
            
            static void MakeDirEmpty(const std::string& path);
            static bool  RemoveFile(const std::string& file);
            static bool RemoveFiles(const std::vector<std::string>& files);
            
            static bool Remove(const std::string& path);
            
            static bool  ExistsFile(const std::string& path);

            
            static bool  ExistsDir(const std::string& path);

            
            static bool  ExistsPath(const std::string& path);


            
            static bool CopyDirectory(const std::string& strSourceDir, const std::string& strDestDir, bool iscopyblk = true, std::string extension = BLOCKFILE);
            static bool CopySingleFile(std::string file, std::string outfile);
            
            static bool CopyFiles(std::vector<std::string> files, std::string out, bool bremovefile = true);
            
            static void BackupFile(std::string srcfile,std::string extensionadded = ".bak");
            static bool RenameFile();
            static bool IsNetFile(const std::string& path);
            static bool CheckNetPathExists(const std::string& path);

            /** UTF-8 narrow string <-> std::filesystem::path (via std::filesystem::u8path). */
            static std::filesystem::path BoostPathFromUtf8(const std::string& utf8Path);
            static std::string BoostPathToUtf8String(const std::filesystem::path& path);

            /** Read entire file; utf8Path is UTF-8. Uses path-aware ifstream (no wchar_t in app code). */
            static bool ReadBinaryFileUtf8(const std::string& utf8Path, std::vector<unsigned char>& out);
            
            static void  CreateDirIfNotExists(const std::string& path, bool bdeepcreate = false);
            static std::string  GetFileName(const std::string& path);
            
            static std::string  GetPathBaseName(const std::string& path);

            static std::string GetFileNameWithoutExtension(const std::string& path);

            
            static std::string   GetParentDir(const std::string& path);
            
            static  std::string EnsureDirectorySlash(const std::string& aFile);
           
            
            
            template <typename... T>
            std::string static JoinPaths(T const&... paths);

            
            static std::vector<std::string> GetFileList(const std::string& path,std::string mask="*.*");

            
            static std::vector<std::string> GetRecursiveFileList(const std::string& path, std::string mask = "*.*");
            
            static void FindDeepsestDir(const std::string& path, std::vector<std::string>& lastdirfiles);

            
            static std::vector<std::string> GetDirList(const std::string& path);

            
            static std::vector<std::string> GetRecursiveDirList(const std::string& path);

            
            static size_t  GetFileSize(const std::string& path);

            /** UTF-8 path via C++17 std::filesystem::u8path (path-aware fstreams; no manual wchar_t). */
            static std::ifstream OpenIfstreamUtf8(const std::string& utf8Path, std::ios::openmode mode = std::ios::in);
            static std::ofstream OpenOfstreamUtf8(const std::string& utf8Path, std::ios::openmode mode = std::ios::out);

            /** UTF-8 lock path: open for write with deny-write sharing on Windows (_SH_DENYWR). Caller must fclose. nullptr on failure. */
            static FILE* FopenDenyWriteLockUtf8(const std::string& utf8LockPath);

            static std::string GetFileExtension(const std::string& path);

            
            static void  PrintHeading1(const std::string& heading);

            
            static void  PrintHeading2(const std::string& heading);
           
            
            template <typename T>
            bool static VectorContainsValue(const std::vector<T>& vector, const T value);

            template <typename T>
            bool static VectorContainsDuplicateValues(const std::vector<T>& vector);

            
            template <typename T>
            std::vector<T> static  CSVToVector(const std::string& csv);

            
            template <typename T>
            std::string static VectorToCSV(const std::vector<T>& values);

            
            template <typename T>
            void static ReadBinaryBlob(const std::string& path, std::vector<T>* data);

            
            template <typename T>
            void static WriteBinaryBlob(const std::string& path, const std::vector<T>& data);

            
            
            std::vector<std::string> static ReadTextFileLines(const std::string& path);
        };
            
            
            
        
            template <typename... T>
            std::string File::JoinPaths(T const&... paths)
            {
                try
                {
                    std::filesystem::path result;
                    int unpack[]{ 0, (result /= File::BoostPathFromUtf8(detail::JoinPathUtf8Segment(paths)), 0)... };
                    static_cast<void>(unpack);
                    return String::StringReplace(File::BoostPathToUtf8String(result), "\\", "/");
                }
                catch (const std::filesystem::filesystem_error& fse)
                {
                    std::ostringstream oss;
                    oss << "fse error:" << fse.code() << " " << fse.what() << " " << fse.path1() << " " << fse.path2();
                    LOGI(oss.str());
                    return "";
                }
                catch (std::exception& ex)
                {
                    std::ostringstream oss;
                    oss << "exception:" << ex.what();
                    LOGI(oss.str());
                    return "";
                }
            }

            template <typename T>
            bool File::VectorContainsValue(const std::vector<T>& vector, const T value) {
                return std::find_if(vector.begin(), vector.end(), [value](const T element) {
                    return element == value;
                    }) != vector.end();
            }

            template <typename T>
            bool File::VectorContainsDuplicateValues(const std::vector<T>& vector) {
                std::vector<T> unique_vector = vector;
                return std::unique(unique_vector.begin(), unique_vector.end()) !=
                    unique_vector.end();
            }

            template <typename T>
            std::string File::VectorToCSV(const std::vector<T>& values) {
                std::string string;
                for (const T value : values) {
                    string += std::to_string(value) + ", ";
                }
                return string.substr(0, string.length() - 2);
            }

            template <typename T>
            void File::ReadBinaryBlob(const std::string& path, std::vector<T>* data) {
                std::ifstream file = OpenIfstreamUtf8(path, std::ios::binary | std::ios::ate);
                if (!CHECK_OPTION(file.is_open()))
                {
                    LOGE("open " + path + "failed.");
                    return;
               }

               
                    
                file.seekg(0, std::ios::end);
                const size_t num_bytes = file.tellg();
                CHECK_OPTION_EQ(num_bytes % sizeof(T), 0);
                data->resize(num_bytes / sizeof(T));
                file.seekg(0, std::ios::beg);
                ReadBinaryLittleEndian<T>(&file, data);
            }

            template <typename T>
            void File::WriteBinaryBlob(const std::string& path, const std::vector<T>& data)
            {
                std::ofstream file = OpenOfstreamUtf8(path, std::ios::binary | std::ios::out);
                if (!CHECK_OPTION(file.is_open()))
                {
                    LOGE("open " + path + "failed.");
                    return;
                }
                WriteBinaryLittleEndian<T>(&file, data);


            }
       
    }
}
#endif  
