/**
  * @file      ExportATColmapDia.h
  * @brief     导出xml界面类
  * @details
  * @attention
  */
#ifndef _AI3D_GUI_EXPORTATCOLMAPDIA_H
#define _AI3D_GUI_EXPORTATCOLMAPDIA_H


#include <QDialog>
#include<QStandardItemModel>
#include "ui_ExportATColmapWgt.h"
#include "Gui/QSensorIntDelegate.h"
#include "Core/CoordinateSystem.h"

namespace AI3D
{
	namespace GUI
	{
		class ExportATColmapDia : public QDialog
		{
			Q_OBJECT
		public:
			ExportATColmapDia(QDialog* parent = Q_NULLPTR);
			~ExportATColmapDia();
			//void InitSrss(QString srsdefination, bool bSetCurrentItem4Recent = false);
			//弹出打开文件对话框
			void openInFileDialog();
			void openOutFileDialog();
			void setOldFileName(QString strFile);
			//QString getFilePath();		
		
			
			void SetOutFileFullName(QString filename);
			void SetInFileFullName(QString filename);
			QString GetOutFileFullName() { return ui.le_path->text(); };
			QString GetInFileFullName() { return ui.le_path_7->text(); };
			void ShowProgress();
			void FinhshWriteXml(int result);
			void Slot_LinkActivated_Label_OpenFolder();
			void SetTabWidgetIndex(int index);
			//void SetEnuId(int id) { EmportEnuID = id; };

			void SetInitFileName(QString filePath,QString fileName);			
			void SetFileParentDir(QString str);
			void Slot_FilePathEdited();
			void AutoGeneratedFullFilePath();

		public slots:

		signals:
			//void sig_VecString(QVector<QStringList> );
			//void sign_posFileReadError();
			void WriteATColmapFile();

		private:
			Ui::ExportATColmapWgt ui;
			QString oldFileName;
			//QString posFile_path;
			//
			//QMap<int, QString> m_RecordMap;
			////QStandardItemModel* model;
			//int EmportEnuID;
			QString initFileName;
			QString initFilePath;
			QString currFileName;
			QString currFilePath;
			QString fullFilePath;
			bool bFilePathHasEdited;

			QString inputFilePath;
			QString outputFilePath;
			/*QString saved_srsdefination;
			QString previous_srs;*/
		};
	}
}
#endif