/**
  * @file      Reconstration.h
  * @brief     导出xml界面类
  * @details
  * @author    李跃
  * @attention
  */
#ifndef _AI3D_GUI_EXPORTXMLDIA_H
#define _AI3D_GUI_EXPORTXMLDIA_H


#include <QDialog>
#include<QStandardItemModel>
#include "ui_ExportXmlWgt.h"
#include "Gui/QSensorIntDelegate.h"
#include "Core/CoordinateSystem.h"

namespace AI3D
{
	namespace GUI
	{
		class ExportXmlDia : public QDialog
		{
			Q_OBJECT
		public:
			ExportXmlDia(QDialog* parent = Q_NULLPTR);
			~ExportXmlDia();
			void InitSrss(QString srsdefination, bool bSetCurrentItem4Recent = false);
			//弹出打开文件对话框
			void openFileDialog();
			void setOldFileName(QString strFile);
			QString getFilePath();		
		
			
			QString GetSrsName();
			bool isSelectTiePoint();
			void SetOutFileFullName(QString filename);
			QString GetOutFileFullName() { return ui.le_path->text(); };
			srs_s GetSelectSrs_s();
			void ShowProgress();
			void FinhshWriteXml();
			void Slot_LinkActivated_Label_OpenFolder();
			void SetTabWidgetIndex(int index);
			void SetCanSelectTiePoint(bool flag);
			void SetEnuId(int id) { EmportEnuID = id; };

			void SetInitFileName(QString filePath,QString fileName);			
			void SetFileParentDir(QString str);
			void Slot_FilePathEdited();
			void AutoGeneratedFullFilePath();

		public slots:
			void Slot_SrsItemChanged(QString srsname);
			void Slot_SrsSelected(QString& srs);
			void Slot_SrsRestore();

		signals:
			//void sig_VecString(QVector<QStringList> );
			void sign_posFileReadError();
			void WriteXmlFile();
		private:
			Ui::ExportXmlWgt ui;
			QString oldFileName;
			QString posFile_path;
			
			QMap<int, QString> m_RecordMap;
			//QStandardItemModel* model;
			int EmportEnuID;
			QString initFileName;
			QString initFilePath;
			QString currFileName;
			QString currFilePath;
			QString fullFilePath;
			bool bFilePathHasEdited;
			QString saved_srsdefination;
			QString previous_srs;
		};
	}
}
#endif